#cloud-config
autoinstall:
  version: 1
  
  # System Configuration
  locale: pt_BR.UTF-8
  keyboard:
    layout: us  # Using basic US layout during installation
  network:
    version: 2
    ethernets:
      default:
        match:
          name: en*
        dhcp4: true
        dhcp6: true
  storage:
    layout:
      name: direct
    swap:
      size: 0
      
  # User Configuration
  identity:
    hostname: PC-MODELO-BL03
    username: informatica
    password: "$y$j9T$65N2vzS81bOBy6righB.a1$mI9E9hcsdUvKetb8DRgR9Z5joxRE7O8TU9.qe/czdgB"

  # System Preparation
  early-commands:
    - sudo systemctl stop unattended-upgrades || true
    - sudo systemctl disable --now apt-daily.timer apt-daily.service apt-daily-upgrade.timer apt-daily-upgrade.service || true
    - sudo timedatectl set-timezone America/Fortaleza
    - sudo apt-get remove -y firefox || true
    - |
      # Add VirtualBox repository
      wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
      sudo apt update

  # Package Installation
  packages:
    - build-essential
    - git
    - curl
    - default-jdk
    - gcc
    - g++
    - gedit
    - make
    - gnat
    - zlib1g-dev
    - gnupg2
    - unzip
    - xz-utils
    - zip
    - dialog
    - libglu1-mesa
    - libxcb-xinerama0-dev
    - ca-certificates
    - clang
    - gtkwave
    - traceroute
    - wireshark
    - snapd
    - postgresql
    - pgadmin4-desktop
    - virtualbox-7.0
    - language-pack-pt
    - language-pack-gnome-pt
    - hunspell-pt-br

  # Snap Packages
  snaps:
    - name: code
      channel: stable
      classic: true
    - name: eclipse
      channel: latest/stable
      classic: true
    - name: flutter
      channel: stable
      classic: true
    - name: android-studio
      channel: stable
      classic: true

  # Post-Install Configuration
  user-data:
    disable_root: false
    runcmd:
      - |
        # Configure Brazilian ABNT2 keyboard
        sudo sed -i 's/XKBLAYOUT=.*/XKBLAYOUT="br"/' /etc/default/keyboard
        sudo sed -i 's/XKBVARIANT=.*/XKBVARIANT="abnt2"/' /etc/default/keyboard
        sudo setupcon -k --force
        
        # Regional configuration
        sudo update-locale LANG=pt_BR.UTF-8 LANGUAGE=pt_BR:pt:en
        sudo localectl set-locale LANG=pt_BR.UTF-8

        # Install MySQL Workbench
        wget https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community_8.0.36-1ubuntu22.04_amd64.deb
        sudo apt install -y ./mysql-workbench-community_8.0.36-1ubuntu22.04_amd64.deb || sudo apt --fix-broken install
        rm mysql-workbench-community_8.0.36-1ubuntu22.04_amd64.deb

        # VirtualBox Extension Pack
        wget -q --show-progress -O /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack \
          https://download.virtualbox.org/virtualbox/7.0.12/Oracle_VM_VirtualBox_Extension_Pack-7.0.12.vbox-extpack
        echo "y" | sudo VBoxManage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack --replace
        rm -f /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack

        # XAMPP Installation
        wget -q --show-progress -O /tmp/xampp-installer.run \
          https://sourceforge.net/projects/xampp/files/XAMPP%20Linux/8.2.12/xampp-linux-x64-8.2.12-0-installer.run/download
        chmod +x /tmp/xampp-installer.run
        sudo /tmp/xampp-installer.run --mode unattended
        sudo /opt/lampp/lampp start
        rm -f /tmp/xampp-installer.run

        # PostgreSQL Configuration
        sudo -u postgres psql -c "CREATE USER informatica WITH PASSWORD 'ifce';"
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'ifce';"
        sudo -u postgres psql -c "CREATE DATABASE informaticadb WITH OWNER informatica;"

        # brModelo Installation
        sudo mkdir -p /opt/brModelo
        sudo wget -q --show-progress -O /opt/brModelo/brModelo.jar \
          http://www.sis4.com/brModelo/brModelo.jar
        sudo wget -q --show-progress -O /opt/brModelo/brModelo.png \
          https://raw.githubusercontent.com/chcandido/brModelo/master/src/imagens/logico.png
        cat > /tmp/brmodelo.desktop <<'EOF'
        [Desktop Entry]
        Version=3.2
        Name=brModelo
        Exec=java -jar /opt/brModelo/brModelo.jar
        Icon=/opt/brModelo/brModelo.png
        Type=Application
        Categories=Development;Education;
        Path=/opt/brModelo
        Terminal=false
        EOF
        sudo mv /tmp/brmodelo.desktop /usr/share/applications/
        sudo chmod +r /usr/share/applications/brmodelo.desktop

        # VS Code Extensions
        for ext in \
          formulahendry.auto-rename-tag \
          naumovs.color-highlight \
          ritwickdey.LiveServer \
          ms-vscode.live-server \
          MS-vsliveshare.vsliveshare \
          GitHub.codespaces \
          Dart-Code.flutter \
          MS-CEINTL.vscode-language-pack-pt-BR \
          vscjava.vscode-java-pack \
          alphabotsec.vscode-eclipse-keybindings
        do
          code --install-extension "$ext" --force
        done

        # Google Chrome
        wget -q --show-progress -O /tmp/google-chrome.deb \
          https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i /tmp/google-chrome.deb || sudo apt-get install -f -y
        rm -f /tmp/google-chrome.deb

        # Logisim Evolution
        wget -q --show-progress -O /tmp/logisim.deb \
          https://github.com/logisim-evolution/logisim-evolution/releases/download/v3.9.0/logisim-evolution_3.9.0_amd64.ubuntu22.04.deb
        sudo dpkg -i /tmp/logisim.deb || sudo apt-get install -f -y
        rm -f /tmp/logisim.deb

        # Additional Tools
        sudo apt-get install -y ghdl gtkwave
        flutter config --enable-linux-desktop
        flutter doctor --android-licenses
        sudo dpkg-reconfigure keyboard-configuration -f noninteractive
        sudo setupcon -k --force

        # Cleanup
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /tmp/*

  # Finalization
  late-commands:
    - sudo systemctl enable postgresql
    - sudo systemctl start postgresql
    - sudo updatedb
    - echo "Instalação concluída com sucesso!"
    - sudo systemctl reboot
